/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ec.vistas;
import java.awt.Dimension;
import static java.awt.Frame.MAXIMIZED_BOTH;
import javax.swing.JInternalFrame;
public class Principal extends javax.swing.JFrame {

    private boolean activador=false;

    
    /**
     * Creates new form Principal
     */
    //Ventana1 VistaTipodeRegistro;
    public Principal() {
       
        initComponents();
        this.setSize(getMaximumSize().width, getMaximumSize().height);
        
        this.setLocationRelativeTo(this);
        VistaTipodeRegistro ObjTipoRegistro =new VistaTipodeRegistro();
        desktopPane.add(ObjTipoRegistro);
        ObjTipoRegistro.setBounds(40, 200, 450, 200);
        ObjTipoRegistro.show();
        
        
        /*Dashboard ObjDashboard = new Dashboard();
        desktopPane.add(ObjDashboard);
        ObjDashboard.setBounds(650, 40, 600, 600);
        ObjDashboard.show();*/
        
        Dashboards ObjDashboards = new Dashboards();
        desktopPane.add(ObjDashboards);
        ObjDashboards.setBounds(650, 50, 600, 600);
        ObjDashboards.show();
       
     /*   menuBar.setEnabled(activador);
        menuBar.setVisible(activador);
        
        Login log = new Login();
        desktopPane.add(log);
        log.show();
        
        
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        loginMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.add(jDesktopPane1);
        jDesktopPane1.setBounds(60, 20, 0, 0);

        jMenu3.setText("Reportes");

        jMenuItem3.setText("Por Proveedor");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem5.setText("Por Rugbro");
        jMenu3.add(jMenuItem5);

        jMenuItem6.setText("Por Fecha");
        jMenu3.add(jMenuItem6);

        menuBar.add(jMenu3);

        jMenu4.setText("Ayuda");
        menuBar.add(jMenu4);

        loginMenu.setMnemonic('h');
        loginMenu.setText("Salir");

        jMenuItem1.setText("Volver al Login");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        loginMenu.add(jMenuItem1);

        jMenuItem7.setText("Salir ");
        loginMenu.add(jMenuItem7);

        menuBar.add(loginMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        
          
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        login objLogin = new login();
        objLogin.setVisible(true);
        this.setVisible(false);
        
    }                                          
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Principal principal = new Principal();

                principal.setExtendedState(MAXIMIZED_BOTH);
                principal.setVisible(true);
                
                
                
            }
        });
    }
    
    // Variables declaration - do not modify                     
    public static javax.swing.JDesktopPane desktopPane;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenu loginMenu;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration                   
}
